# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        architecture:
          - amd64
          - 86x

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup VS Dev Environment
      uses: seanmiddleditch/gha-setup-vsdevenv@v1
      with:
        # Target build architecture
        arch: ${{ matrix.architecture }}
        
    - name: Build project for ${{ matrix.architecture }}
      run: |
          dir
          dir "C:\Program Files (x86)\MSBuild\Microsoft.Cpp"
